/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_v1_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_v1_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Category */
        get: operations["get_category_api_v1_categories__category_id__get"];
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_v1_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_api_v1_categories__category_id__patch"];
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_v1_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_api_v1_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tag */
        get: operations["get_tag_api_v1_tags__tag_id__get"];
        put?: never;
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_api_v1_tags__tag_id__delete"];
        options?: never;
        head?: never;
        /** Update Tag */
        patch: operations["update_tag_api_v1_tags__tag_id__patch"];
        trace?: never;
    };
    "/api/v1/habits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Habits */
        get: operations["list_habits_api_v1_habits_get"];
        put?: never;
        /** Create Habit */
        post: operations["create_habit_api_v1_habits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/habits/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Today
         * @description Sectioned by frequency, each section contains both habits and routines.
         *
         *     Note: path stays /habits/today for backwards-compatibility, but the response
         *     now includes routines too.
         */
        get: operations["list_today_api_v1_habits_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/habits/{habit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Habit */
        get: operations["get_habit_api_v1_habits__habit_id__get"];
        put?: never;
        post?: never;
        /** Delete Habit */
        delete: operations["delete_habit_api_v1_habits__habit_id__delete"];
        options?: never;
        head?: never;
        /** Update Habit */
        patch: operations["update_habit_api_v1_habits__habit_id__patch"];
        trace?: never;
    };
    "/api/v1/habits/{habit_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Habit Stats */
        get: operations["get_habit_stats_api_v1_habits__habit_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/habits/{habit_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Habit Done */
        post: operations["mark_habit_done_api_v1_habits__habit_id__log_post"];
        /** Unmark Habit */
        delete: operations["unmark_habit_api_v1_habits__habit_id__log_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Routines */
        get: operations["list_routines_api_v1_routines_get"];
        put?: never;
        /** Create Routine */
        post: operations["create_routine_api_v1_routines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines/{routine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Routine */
        get: operations["get_routine_api_v1_routines__routine_id__get"];
        put?: never;
        post?: never;
        /** Delete Routine */
        delete: operations["delete_routine_api_v1_routines__routine_id__delete"];
        options?: never;
        head?: never;
        /** Update Routine */
        patch: operations["update_routine_api_v1_routines__routine_id__patch"];
        trace?: never;
    };
    "/api/v1/routines/{routine_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Session */
        post: operations["start_session_api_v1_routines__routine_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines/sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Complete Session */
        patch: operations["complete_session_api_v1_routines_sessions__session_id__complete_patch"];
        trace?: never;
    };
    "/api/v1/routines/{routine_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_v1_routines__routine_id__sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vacations */
        get: operations["list_vacations_api_v1_vacations_get"];
        put?: never;
        /** Create Vacation */
        post: operations["create_vacation_api_v1_vacations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacations/{vacation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vacation */
        get: operations["get_vacation_api_v1_vacations__vacation_id__get"];
        put?: never;
        post?: never;
        /** Delete Vacation */
        delete: operations["delete_vacation_api_v1_vacations__vacation_id__delete"];
        options?: never;
        head?: never;
        /** Update Vacation */
        patch: operations["update_vacation_api_v1_vacations__vacation_id__patch"];
        trace?: never;
    };
    "/api/v1/calendar/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekly */
        get: operations["weekly_api_v1_calendar_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/yearly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yearly */
        get: operations["yearly_api_v1_calendar_yearly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly */
        get: operations["monthly_api_v1_calendar_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_api_v1_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trends */
        get: operations["get_trends_api_v1_stats_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AggregateStatsResponse
         * @description GET /stats/overview — aggregate dashboard data.
         */
        AggregateStatsResponse: {
            /** Overall Completion Rate */
            overall_completion_rate?: number | null;
            /**
             * Active Streak Count
             * @default 0
             */
            active_streak_count: number;
            /**
             * Today Done
             * @default 0
             */
            today_done: number;
            /**
             * Today Total
             * @default 0
             */
            today_total: number;
            /** Top Habits */
            top_habits?: components["schemas"]["HabitSummary"][];
            /** Habits */
            habits?: components["schemas"]["HabitSummary"][];
            /** Avoid Habits */
            avoid_habits?: components["schemas"]["HabitSummary"][];
        };
        /**
         * CalendarDay
         * @description One day's slot in a calendar view.
         *
         *     - `status` is the day-level status (for daily habits) or the day's view of
         *       the containing period (for WEEKLY/MONTHLY/YEARLY habits).
         *     - `amount` is the total amount LOGGED on this specific day. Lets the UI
         *       render gradients (e.g. days with logs = solid color, surrounding days
         *       in a successful week = lighter gradient).
         */
        CalendarDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            status: components["schemas"]["HabitStatus"];
            /**
             * Amount
             * @default 0
             */
            amount: number;
        };
        /**
         * CategoryCreate
         * @description Request body for creating a new category.
         */
        CategoryCreate: {
            /** Name */
            name: string;
        };
        /**
         * CategoryResponse
         * @description Shape of category data returned to the client.
         *     Never includes user_id — the caller already knows who they are.
         */
        CategoryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CategoryUpdate
         * @description Request body for renaming a category.
         */
        CategoryUpdate: {
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HabitCreate
         * @description Request body for creating a new habit.
         *
         *     target_per_period omitted -> mode-aware default in the service:
         *       DO    -> 1 (binary "did it once")
         *       AVOID -> 0 (binary "never logged")
         *
         *     Scheduling rules (validated below):
         *       DAILY     -> no scheduling fields
         *       WEEKLY    -> scheduled_weekdays (empty = flexible / every day)
         *       MONTHLY   -> scheduled_days_of_month (empty = flexible)
         *       YEARLY    -> scheduled_dates (empty = flexible)
         *       INTERVAL  -> interval_days required, every N days from start_date
         */
        HabitCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            mode: components["schemas"]["HabitMode"];
            frequency: components["schemas"]["HabitFrequency"];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            section?: components["schemas"]["HabitSection"] | null;
            /** Category Id */
            category_id?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Archived
             * @default false
             */
            is_archived: boolean;
            /** Target Per Period */
            target_per_period?: number | null;
            /**
             * Increment
             * @default 1
             */
            increment: number;
            /** Scheduled Weekdays */
            scheduled_weekdays?: number[];
            /** Scheduled Days Of Month */
            scheduled_days_of_month?: number[];
            /** Scheduled Dates */
            scheduled_dates?: string[];
            /** Interval Days */
            interval_days?: number | null;
            /** Days Per Week */
            days_per_week?: number | null;
            /** Color Key */
            color_key?: string | null;
            /** Unit */
            unit?: string | null;
            /** Tag Ids */
            tag_ids?: string[];
            /** Routine Ids */
            routine_ids?: string[];
        };
        /**
         * HabitFrequency
         * @description How often a habit is expected.
         *
         *     Period-based: DAILY, WEEKLY, MONTHLY, YEARLY (target tracked across the period).
         *     Interval-based: INTERVAL (every N days from start_date, paired with interval_days).
         *     CUSTOM is reserved for future date-list scheduling.
         * @enum {string}
         */
        HabitFrequency: "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY" | "INTERVAL" | "CUSTOM";
        /**
         * HabitLogCreate
         * @description Request body for logging a habit event.
         *
         *     log_date omitted -> server uses today (UTC). Future dates rejected.
         *     amount   omitted -> server uses habit.increment.
         *     Each POST creates a new row — no idempotency. Use DELETE to undo.
         */
        HabitLogCreate: {
            /** Log Date */
            log_date?: string | null;
            /** Amount */
            amount?: number | null;
        };
        /**
         * HabitLogResponse
         * @description shape of a habit_log row returned to client.
         */
        HabitLogResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Habit Id
             * Format: uuid
             */
            habit_id: string;
            /**
             * Log Date
             * Format: date
             */
            log_date: string;
            /** Amount */
            amount: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * HabitMode
         * @description How a habit is judged:
         *     - DO:    success = marking it done
         *     - AVOID: success = NOT logging it
         * @enum {string}
         */
        HabitMode: "DO" | "AVOID";
        /**
         * HabitResponse
         * @description Shape of habit data returned to the client.
         *     Never includes user_id — the caller already knows who they are.
         */
        HabitResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            mode: components["schemas"]["HabitMode"];
            frequency: components["schemas"]["HabitFrequency"];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            section: components["schemas"]["HabitSection"] | null;
            /** Category Id */
            category_id: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Archived */
            is_archived: boolean;
            /** Target Per Period */
            target_per_period: number;
            /** Increment */
            increment: number;
            /** Scheduled Weekdays */
            scheduled_weekdays: number[];
            /** Scheduled Days Of Month */
            scheduled_days_of_month: number[];
            /** Scheduled Dates */
            scheduled_dates: string[];
            /** Interval Days */
            interval_days: number | null;
            /** Days Per Week */
            days_per_week: number | null;
            /** Color Key */
            color_key: string | null;
            /** Unit */
            unit: string | null;
            /** Tags */
            tags: components["schemas"]["TagResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * HabitSection
         * @description Time-of-day grouping. NULL = appears all day.
         * @enum {string}
         */
        HabitSection: "MORNING" | "AFTERNOON" | "EVENING";
        /**
         * HabitStatsResponse
         * @description Full /stats response for one habit.
         */
        HabitStatsResponse: {
            current_streak: components["schemas"]["StreakInfo"];
            best_streak: components["schemas"]["StreakInfo"];
            /** Periods */
            periods?: {
                [key: string]: components["schemas"]["PeriodStats"];
            };
            records: components["schemas"]["RecordSet"];
        };
        /**
         * HabitStatus
         * @description server-computed view of a habit's state for a given day / period.
         *     Folds DO/AVOID inversion into one enum so clients don't need to know the rule.
         *
         *       DO    + sum>=target          -> SUCCESS
         *       DO    + sum<target, in-prog  -> PENDING
         *       DO    + sum<target, past     -> FAILED
         *       AVOID + sum<=target          -> SUCCESS
         *       AVOID + sum>target           -> FAILED (instant)
         *       not due that day             -> NOT_SCHEDULED  (calendar views only)
         *       date covered by a vacation   -> VACATION       (display override)
         * @enum {string}
         */
        HabitStatus: "SUCCESS" | "PENDING" | "FAILED" | "NOT_SCHEDULED" | "VACATION";
        /**
         * HabitSummary
         * @description Per-habit row in the aggregate stats response.
         *
         *     Streaks and total_events are all-time; completion_rate respects the
         *     requested date range.
         */
        HabitSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Color Key */
            color_key?: string | null;
            /** Mode */
            mode: string;
            /** Frequency */
            frequency: string;
            /** Unit */
            unit?: string | null;
            /** Current Streak */
            current_streak: number;
            /**
             * Best Streak
             * @default 0
             */
            best_streak: number;
            /**
             * Total Events
             * @default 0
             */
            total_events: number;
            /** Completion Rate */
            completion_rate?: number | null;
            /** Days Since Last Slip */
            days_since_last_slip?: number | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /**
         * HabitTodayResponse
         * @description A habit due on the requested date + its computed status.
         */
        HabitTodayResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            mode: components["schemas"]["HabitMode"];
            frequency: components["schemas"]["HabitFrequency"];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            section: components["schemas"]["HabitSection"] | null;
            /** Category Id */
            category_id: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Archived */
            is_archived: boolean;
            /** Target Per Period */
            target_per_period: number;
            /** Increment */
            increment: number;
            /** Scheduled Weekdays */
            scheduled_weekdays: number[];
            /** Scheduled Days Of Month */
            scheduled_days_of_month: number[];
            /** Scheduled Dates */
            scheduled_dates: string[];
            /** Interval Days */
            interval_days: number | null;
            /** Days Per Week */
            days_per_week: number | null;
            /** Color Key */
            color_key: string | null;
            /** Unit */
            unit: string | null;
            /** Tags */
            tags: components["schemas"]["TagResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            status: components["schemas"]["HabitStatus"];
            /** Current Period Count */
            current_period_count: number;
            /** Week Completed Days */
            week_completed_days?: number | null;
        };
        /**
         * HabitUpdate
         * @description Request body for editing a habit.
         *     All fields optional — PATCH semantics. Only sent fields are updated.
         *
         *     If you change `frequency`, you almost certainly also want to send the
         *     matching scheduling fields (and clear the others). The service validates
         *     the resulting combined state after merging with the existing row.
         *
         *     Note on tag_ids: sending [] *clears* all tags; omitting tag_ids leaves them
         *     untouched. The service distinguishes by checking `"tag_ids" in fields`.
         */
        HabitUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            mode?: components["schemas"]["HabitMode"] | null;
            frequency?: components["schemas"]["HabitFrequency"] | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            section?: components["schemas"]["HabitSection"] | null;
            /** Category Id */
            category_id?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Archived */
            is_archived?: boolean | null;
            /** Target Per Period */
            target_per_period?: number | null;
            /** Increment */
            increment?: number | null;
            /** Scheduled Weekdays */
            scheduled_weekdays?: number[] | null;
            /** Scheduled Days Of Month */
            scheduled_days_of_month?: number[] | null;
            /** Scheduled Dates */
            scheduled_dates?: string[] | null;
            /** Interval Days */
            interval_days?: number | null;
            /** Days Per Week */
            days_per_week?: number | null;
            /** Color Key */
            color_key?: string | null;
            /** Unit */
            unit?: string | null;
            /** Tag Ids */
            tag_ids?: string[] | null;
            /** Routine Ids */
            routine_ids?: string[] | null;
        };
        /**
         * MonthlyCalendarResponse
         * @description Full month view for a single habit.
         */
        MonthlyCalendarResponse: {
            habit: components["schemas"]["HabitResponse"];
            /** Month */
            month: string;
            /** Days */
            days: components["schemas"]["CalendarDay"][];
            summary: components["schemas"]["MonthlySummary"];
        };
        /**
         * MonthlySummary
         * @description Aggregate stats for a habit across a single month.
         *     Cheap server-side counts so clients don't have to loop.
         *     # TODO: add streak fields in Step 12 (current_streak, best_streak_this_month)
         */
        MonthlySummary: {
            /** Scheduled Days */
            scheduled_days: number;
            /** Successful Days */
            successful_days: number;
            /** Failed Days */
            failed_days: number;
            /** Pending Days */
            pending_days: number;
            /** Success Rate */
            success_rate: number;
        };
        /**
         * PeriodStats
         * @description Stats for one view (day/week/month/year/all_time).
         *
         *     events            -> sum of logged amounts in the view's date range (volume)
         *     expected          -> target_per_period * number of habit periods in range
         *                          (null when the view is narrower than the habit's period,
         *                           e.g. "day" view of a WEEKLY habit on a non-Monday)
         *     periods_succeeded -> judged periods in range where the target was met
         *     periods_total     -> judged periods (SUCCESS or FAILED — the in-progress
         *                          PENDING period and vacation-exempt periods don't count)
         *     completion_rate   -> periods_succeeded / periods_total. Period-success
         *                          based: overshooting one period can't push it past 1.0.
         *                          Meaningful for both DO and AVOID (clean-period rate).
         *                          Null when no period has been judged yet.
         */
        PeriodStats: {
            /** Events */
            events: number;
            /** Expected */
            expected?: number | null;
            /**
             * Periods Succeeded
             * @default 0
             */
            periods_succeeded: number;
            /**
             * Periods Total
             * @default 0
             */
            periods_total: number;
            /** Completion Rate */
            completion_rate?: number | null;
        };
        /** RecordMonth */
        RecordMonth: {
            /** Month */
            month: string;
            /** Count */
            count: number;
        };
        /**
         * RecordSet
         * @description Personal records: top-event months and years.
         *     Only populated for DO habits — "best month" for AVOID is conceptually the
         *     month with FEWEST logs, which is too easy to game by simply not opening
         *     the app. Skip records for AVOID for now.
         */
        RecordSet: {
            best_month?: components["schemas"]["RecordMonth"] | null;
            best_year?: components["schemas"]["RecordYear"] | null;
        };
        /** RecordYear */
        RecordYear: {
            /** Year */
            year: string;
            /** Count */
            count: number;
        };
        /**
         * RefreshRequest
         * @description resquest body for the /refresh endpoint
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RoutineCreate
         * @description Request body for creating a new routine.
         */
        RoutineCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            frequency: components["schemas"]["RoutineFrequency"];
            /** Scheduled Weekdays */
            scheduled_weekdays?: number[];
            /** Scheduled Days Of Month */
            scheduled_days_of_month?: number[];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /** Habits */
            habits?: components["schemas"]["RoutineHabitSlotInput"][];
        };
        /**
         * RoutineFrequency
         * @description Routines have a narrower set than habits — no YEARLY / INTERVAL / CUSTOM
         *     and no "flexible / any day" mode. Routines are always either DAILY or
         *     anchored to specific days within a week/month.
         * @enum {string}
         */
        RoutineFrequency: "DAILY" | "WEEKLY" | "MONTHLY";
        /**
         * RoutineHabitSlotInput
         * @description One slot in a routine, as supplied by the client.
         */
        RoutineHabitSlotInput: {
            /**
             * Habit Id
             * Format: uuid
             */
            habit_id: string;
            /** Timer Seconds */
            timer_seconds?: number | null;
            timer_type?: components["schemas"]["RoutineTimerType"] | null;
        };
        /**
         * RoutineHabitSlotResponse
         * @description One slot returned to the client. Includes the full habit inline so the
         *     UI doesn't have to make N extra calls to render the routine.
         */
        RoutineHabitSlotResponse: {
            habit: components["schemas"]["HabitResponse"];
            /** Position */
            position: number;
            /** Timer Seconds */
            timer_seconds: number | null;
            timer_type: components["schemas"]["RoutineTimerType"] | null;
        };
        /**
         * RoutineResponse
         * @description Full routine shape with habits inline.
         */
        RoutineResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Is Active */
            is_active: boolean;
            frequency: components["schemas"]["RoutineFrequency"];
            /** Scheduled Weekdays */
            scheduled_weekdays: number[];
            /** Scheduled Days Of Month */
            scheduled_days_of_month: number[];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            /** Habits */
            habits?: components["schemas"]["RoutineHabitSlotResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RoutineSessionResponse
         * @description Session row + computed status & duration so the client doesn't have to.
         */
        RoutineSessionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Routine Id
             * Format: uuid
             */
            routine_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Abandoned At */
            abandoned_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            readonly status: components["schemas"]["RoutineSessionStatus"];
            /** Duration Seconds */
            readonly duration_seconds: number | null;
        };
        /**
         * RoutineSessionStatus
         * @description Computed from the session's timestamps. Never stored.
         * @enum {string}
         */
        RoutineSessionStatus: "IN_PROGRESS" | "COMPLETED" | "ABANDONED";
        /**
         * RoutineTimerType
         * @description How a slot's timer behaves during a routine playthrough.
         *
         *     TIMER     (0 -> n stopwatch): exclusive — starting another habit cancels it.
         *                                   Used for hands-busy tasks (e.g. brush teeth).
         *     COUNTDOWN (n -> 0): can run in parallel with other countdowns and other
         *                         habit interactions (e.g. face mask while doing other steps).
         *
         *     Enforcement of the exclusivity rule lives on the client; backend stores
         *     the type so the UI knows which rule to apply.
         * @enum {string}
         */
        RoutineTimerType: "TIMER" | "COUNTDOWN";
        /**
         * RoutineTodayResponse
         * @description A routine due on the requested date, plus its computed status.
         */
        RoutineTodayResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Is Active */
            is_active: boolean;
            frequency: components["schemas"]["RoutineFrequency"];
            /** Scheduled Weekdays */
            scheduled_weekdays: number[];
            /** Scheduled Days Of Month */
            scheduled_days_of_month: number[];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            /** Habits */
            habits?: components["schemas"]["RoutineHabitSlotResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            status: components["schemas"]["HabitStatus"];
        };
        /**
         * RoutineUpdate
         * @description PATCH semantics. Sending `habits` REPLACES the full slot list.
         *     Omit `habits` to leave existing slots untouched.
         */
        RoutineUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            frequency?: components["schemas"]["RoutineFrequency"] | null;
            /** Scheduled Weekdays */
            scheduled_weekdays?: number[] | null;
            /** Scheduled Days Of Month */
            scheduled_days_of_month?: number[] | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Habits */
            habits?: components["schemas"]["RoutineHabitSlotInput"][] | null;
        };
        /**
         * StreakInfo
         * @description length is 0 when there's no streak; dates are null in that case.
         */
        StreakInfo: {
            /** Length */
            length: number;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /**
         * TagCreate
         * @description Request body for creating a new tag.
         */
        TagCreate: {
            /** Name */
            name: string;
        };
        /**
         * TagResponse
         * @description Shape of tag data returned to the client.
         *     Never includes user_id — the caller already knows who they are.
         */
        TagResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TagUpdate
         * @description Request body for renaming a tag.
         */
        TagUpdate: {
            /** Name */
            name: string;
        };
        /**
         * TodayResponse
         * @description Top-level /today response, split into sections.
         *
         *     YEARLY routines don't exist by design — that section's `routines` is
         *     always empty. INTERVAL is habits-only for the same reason.
         */
        TodayResponse: {
            daily?: components["schemas"]["TodaySection"];
            weekly?: components["schemas"]["TodaySection"];
            monthly?: components["schemas"]["TodaySection"];
            yearly?: components["schemas"]["TodaySection"];
            interval?: components["schemas"]["TodaySection"];
        };
        /**
         * TodaySection
         * @description One frequency bucket — both habits and routines for that cadence.
         */
        TodaySection: {
            /** Habits */
            habits?: components["schemas"]["HabitTodayResponse"][];
            /** Routines */
            routines?: components["schemas"]["RoutineTodayResponse"][];
        };
        /**
         * TokenResponse
         * @description returned after login or token refresh
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TrendPoint
         * @description One data point in the trends time series.
         */
        TrendPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Rate */
            rate: number;
        };
        /**
         * TrendsResponse
         * @description GET /stats/trends — time-series completion rates.
         */
        TrendsResponse: {
            /** Overall */
            overall?: components["schemas"]["TrendPoint"][];
            /** Per Habit */
            per_habit?: {
                [key: string]: components["schemas"]["TrendPoint"][];
            };
        };
        /**
         * UserCreate
         * @description shape of the request body for register and login
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserResponse
         * @description shape of the response when returning user data
         *     never includes hashed_password
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * VacationCreate
         * @description Request body for a new vacation period.
         */
        VacationCreate: {
            /** Name */
            name?: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
        };
        /** VacationResponse */
        VacationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * VacationUpdate
         * @description All fields optional — PATCH semantics.
         */
        VacationUpdate: {
            /** Name */
            name?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WeeklyCalendarItem
         * @description One row in the weekly grid: a habit and its 7-day status strip.
         */
        WeeklyCalendarItem: {
            habit: components["schemas"]["HabitResponse"];
            /** Days */
            days: components["schemas"]["CalendarDay"][];
        };
        /**
         * YearlyCalendarItem
         * @description One row in the yearly grid: a habit and its 365/366-day status strip.
         */
        YearlyCalendarItem: {
            habit: components["schemas"]["HabitResponse"];
            /** Days */
            days: components["schemas"]["CalendarDay"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
        };
    };
    create_category_api_v1_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_api_v1_categories__category_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_v1_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_v1_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_v1_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"][];
                };
            };
        };
    };
    create_tag_api_v1_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tag_api_v1_tags__tag_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_api_v1_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_api_v1_tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_habits_api_v1_habits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitResponse"][];
                };
            };
        };
    };
    create_habit_api_v1_habits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_today_api_v1_habits_today_get: {
        parameters: {
            query?: {
                /** @description Calendar day to check (YYYY-MM-DD). Defaults to UTC today. */
                date?: string | null;
                /** @description Client's current hour (0-23) for time-of-day section filtering. */
                hour?: number | null;
                /** @description 'today' = habits due on the date. 'week'/'month'/'year' = every habit belonging to that tab, even if not scheduled on the date. */
                scope?: "today" | "week" | "month" | "year";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_habit_api_v1_habits__habit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_habit_api_v1_habits__habit_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_habit_api_v1_habits__habit_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_habit_stats_api_v1_habits__habit_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_habit_done_api_v1_habits__habit_id__log_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habit_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["HabitLogCreate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unmark_habit_api_v1_habits__habit_id__log_delete: {
        parameters: {
            query?: {
                /** @description Day to unmark (YYYY-MM-DD). Defaults to UTC today. */
                date?: string | null;
            };
            header?: never;
            path: {
                habit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_routines_api_v1_routines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineResponse"][];
                };
            };
        };
    };
    create_routine_api_v1_routines_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_routine_api_v1_routines__routine_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_routine_api_v1_routines__routine_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_routine_api_v1_routines__routine_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_api_v1_routines__routine_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_session_api_v1_routines_sessions__session_id__complete_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_routines__routine_id__sessions_get: {
        parameters: {
            query: {
                /** @description YYYY-MM */
                month: string;
            };
            header?: never;
            path: {
                routine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineSessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vacations_api_v1_vacations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacationResponse"][];
                };
            };
        };
    };
    create_vacation_api_v1_vacations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vacation_api_v1_vacations__vacation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_vacation_api_v1_vacations__vacation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vacation_api_v1_vacations__vacation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weekly_api_v1_calendar_weekly_get: {
        parameters: {
            query?: {
                /** @description Any day in the week to view (YYYY-MM-DD). Server anchors to Monday. Defaults to UTC today. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyCalendarItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yearly_api_v1_calendar_yearly_get: {
        parameters: {
            query: {
                /** @description Year to view (e.g. 2026). */
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearlyCalendarItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monthly_api_v1_calendar_monthly_get: {
        parameters: {
            query: {
                /** @description The habit to fetch the month for. */
                habit_id: string;
                /** @description YYYY-MM */
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyCalendarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_api_v1_stats_overview_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregateStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trends_api_v1_stats_trends_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                habit_id?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
