"""habit scheduling: arrays, yearly, interval

Revision ID: d9d59697c68c
Revises: dc3d295b532c
Create Date: 2026-06-04 21:54:56.722717+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9d59697c68c'
down_revision: Union[str, None] = 'dc3d295b532c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE habit_frequency ADD VALUE IF NOT EXISTS 'YEARLY'")
    op.execute("ALTER TYPE habit_frequency ADD VALUE IF NOT EXISTS 'INTERVAL'")
    op.add_column('habits', sa.Column('scheduled_weekdays', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.add_column('habits', sa.Column('scheduled_days_of_month', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.add_column('habits', sa.Column('scheduled_dates', postgresql.ARRAY(sa.String(length=5)), server_default='{}', nullable=False))
    op.add_column('habits', sa.Column('interval_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'interval_days')
    op.drop_column('habits', 'scheduled_dates')
    op.drop_column('habits', 'scheduled_days_of_month')
    op.drop_column('habits', 'scheduled_weekdays')
    # Note: YEARLY / INTERVAL enum values are left in place. Since removing enum
    # values in Postgres requires recreating the type — it was skipped here.
    # ### end Alembic commands ###
