"""habit: color_key + unit columns

Revision ID: feb6af03bd19
Revises: 642c0200d710
Create Date: 2026-06-07 22:16:30.611682+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb6af03bd19'
down_revision: Union[str, None] = '642c0200d710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('color_key', sa.String(length=50), nullable=True))
    op.add_column('habits', sa.Column('unit', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'unit')
    op.drop_column('habits', 'color_key')
    # ### end Alembic commands ###
