"""quantified habits: target_per_period, increment, log amount, drop unique

Revision ID: dc3d295b532c
Revises: 27bd2375a2d5
Create Date: 2026-06-04 21:44:47.518616+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3d295b532c'
down_revision: Union[str, None] = '27bd2375a2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_logs', sa.Column('amount', sa.Float(), server_default='1.0', nullable=False))
    op.drop_constraint('uq_habit_logs_habit_date', 'habit_logs', type_='unique')
    op.add_column('habits', sa.Column('target_per_period', sa.Integer(), server_default='1', nullable=False))
    op.add_column('habits', sa.Column('increment', sa.Float(), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'increment')
    op.drop_column('habits', 'target_per_period')
    op.create_unique_constraint('uq_habit_logs_habit_date', 'habit_logs', ['habit_id', 'log_date'], postgresql_nulls_not_distinct=False)
    op.drop_column('habit_logs', 'amount')
    # ### end Alembic commands ###
