import enum
import uuid
from datetime import date, datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
	Boolean,
	Date,
	DateTime,
	Enum as SQLEnum,
	ForeignKey,
	String,
	UniqueConstraint,
	func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

from app.models.habit_tag import habit_tags

if TYPE_CHECKING:
	# only imported during type-checking (mypy), not at runtime
	# prevents circular imports
	from app.models.category import Category
	from app.models.tag import Tag
	from app.models.user import User
	from app.models.habit_log import HabitLog


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------
# str + enum.Enum => values serialize as plain strings ("DO", "DAILY") in JSON
# and round-trip cleanly through Pydantic / Postgres.

class HabitMode(str, enum.Enum):
	"""How a habit is judged:
	  - DO:    success = marking it done
	  - AVOID: success = NOT logging it
	"""
	DO = "DO"
	AVOID = "AVOID"


class HabitFrequency(str, enum.Enum):
	"""How often a habit is expected.
	CUSTOM leaves room for future per-habit interval rules (e.g. every 3 days).
	"""
	DAILY = "DAILY"
	WEEKLY = "WEEKLY"
	MONTHLY = "MONTHLY"
	CUSTOM = "CUSTOM"


"""
structure formula
column_name: Mapped[python_type] = mapped_column(
	DB_TYPE,		# type Postgres stores as
	...options...	# constraints, defaults, behaviour
)
"""
class Habit(Base):
	__tablename__ = "habits"

	id: Mapped[uuid.UUID] = mapped_column(
		UUID(as_uuid=True),
		primary_key=True,
		default=uuid.uuid4,
	)
	name: Mapped[str] = mapped_column(
		String(100),
		nullable=False,
	)
	description: Mapped[str | None] = mapped_column(
		String(500),
		nullable=True,				# optional longer text — e.g. "drink 2L before noon"
	)
	mode: Mapped[HabitMode] = mapped_column(
		SQLEnum(HabitMode, name="habit_mode"),
		# name="habit_mode" -> name of the enum TYPE Postgres creates internally.
		# without it, alembic gives the type an autogenerated name we can't control.
		nullable=False,
	)
	frequency: Mapped[HabitFrequency] = mapped_column(
		SQLEnum(HabitFrequency, name="habit_frequency"),
		nullable=False,
	)
	start_date: Mapped[date] = mapped_column(
		Date,						# Date (no time) — we only care about calendar days
		nullable=False,
	)
	end_date: Mapped[date | None] = mapped_column(
		Date,
		nullable=True,				# optional — terminal vs ongoing habits
	)
	is_active: Mapped[bool] = mapped_column(
		Boolean,
		default=True,				# new habits start active; user can pause without deleting
		nullable=False,
	)
	user_id: Mapped[uuid.UUID] = mapped_column(
		UUID(as_uuid=True),
		ForeignKey("users.id", ondelete="CASCADE"),
		# CASCADE: delete a user -> delete all their habits
		nullable=False,
		index=True,
	)
	category_id: Mapped[uuid.UUID] = mapped_column(
		UUID(as_uuid=True),
		ForeignKey("categories.id", ondelete="RESTRICT"),
		# RESTRICT: postgres will REFUSE to delete a category that still has habits.
		# forces the user to reassign or delete the habits first -> prevents accidents.
		nullable=False,
		index=True,
	)
	created_at: Mapped[datetime] = mapped_column(
		DateTime(timezone=True),
		server_default=func.now(),
		nullable=False,
	)
	updated_at: Mapped[datetime] = mapped_column(
		DateTime(timezone=True),
		server_default=func.now(),
		onupdate=func.now(),
		nullable=False,
	)

	# ORM relationships
	# habit.user     -> the full User object
	# habit.category -> the full Category object
	# habit.tags     -> list of Tag objects (joined via habit_tags table)
	user: Mapped["User"] = relationship("User", back_populates="habits")
	category: Mapped["Category"] = relationship("Category")
	tags: Mapped[list["Tag"]] = relationship(
		"Tag",
		secondary=habit_tags,		# go through this join table
		back_populates="habits",
	)
	logs: Mapped[list["HabitLog"]] = relationship(
		"HabitLog",
		back_populates="habit",
		cascade="all, delete-orphan",
	)

	# same user can't have two habits with the same name (case-sensitive)
	__table_args__ = (
		UniqueConstraint("user_id", "name", name="uq_habits_user_name"),
	)
